const fetch = require('node-fetch');

const GITHUB_API = 'https://api.github.com';

function getHeaders() {
  return {
    'Authorization': `Bearer ${process.env.GITHUB_TOKEN}`,
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  };
}

function getOrg() {
  return process.env.GITHUB_ORG || 'askboppana';
}

function getCiTemplate(stack, orgName) {
  const workflowMap = {
    java:       '_deploy.yml',
    javascript: '_deploy.yml',
    python:     '_deploy.yml',
    dotnet:     '_deploy.yml',
    uipath:     '_deploy.yml',
    salesforce: '_deploy.yml',
    default:    '_deploy.yml',
  };

  const workflow = workflowMap[stack] || workflowMap.default;

  return `# ForgeOps CI/CD Pipeline
# Auto-generated by ForgeOps onboarding
# Triggers on push to feature branches and PRs to environment branches
name: CI/CD

on:
  push:
    branches: ['feature/*', 'hotfix/*']
  pull_request:
    branches: [int, qa, stage, main]
    types: [closed]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options: [int, qa, stage, prod]

jobs:
  pipeline:
    uses: ${orgName}/ForgeOps/.github/workflows/${workflow}@main
    with:
      app_name: \${{ github.event.repository.name }}
      version: \${{ github.sha }}
      environment: \${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'int' }}
    secrets: inherit
`;
}

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
};

function respond(statusCode, body) {
  return {
    statusCode,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    body: JSON.stringify(body)
  };
}

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') return { statusCode: 200, headers: corsHeaders, body: '' };

    const fullPath = event.path || '';
  const pathParts = fullPath.split('/').filter(Boolean);
  // Find 'onboarding' in path and take everything after it
  let segments = [];
  for (let i = 0; i < pathParts.length; i++) {
    if (pathParts[i] === 'onboarding') {
      segments = pathParts.slice(i + 1);
      break;
    }
  }
  const method = event.httpMethod;
  const body = event.body ? JSON.parse(event.body) : {};
  const query = event.queryStringParameters || {};

  try {
    // POST /add-ci
    if (segments[0] === 'add-ci' && method === 'POST') {
      const { owner, repo, stack } = body;
      const org = owner || getOrg();
      const template = getCiTemplate(stack || 'default', org);
      const content = Buffer.from(template).toString('base64');

      console.log(`Onboarding: adding ci.yml to ${org}/${repo}`);

      // Check if file already exists
      const checkRes = await fetch(
        `${GITHUB_API}/repos/${org}/${repo}/contents/.github/workflows/ci.yml`,
        { headers: getHeaders() }
      );

      if (checkRes.status === 200) {
        const existing = await checkRes.json();
        return respond(200, {
          status: 'exists',
          message: `${repo} already has .github/workflows/ci.yml`,
          sha: existing.sha,
        });
      }

      // Create the file
      const createRes = await fetch(
        `${GITHUB_API}/repos/${org}/${repo}/contents/.github/workflows/ci.yml`,
        {
          method: 'PUT',
          headers: getHeaders(),
          body: JSON.stringify({
            message: 'chore: add ForgeOps CI/CD pipeline [skip ci]',
            content: content,
          }),
        }
      );

      const data = await createRes.json();

      if (createRes.status === 201) {
        console.log(`Onboarded: ${org}/${repo}`);
        return respond(200, {
          status: 'created',
          message: `CI template added to ${repo}`,
          sha: data.content?.sha,
          url: data.content?.html_url,
        });
      } else {
        console.error(`Onboard failed for ${repo}:`, createRes.status, data.message);
        return respond(createRes.status, {
          status: 'error',
          message: data.message || 'Failed to create file',
        });
      }
    }

    // POST /bulk
    if (segments[0] === 'bulk' && method === 'POST') {
      const { repos, stack } = body;
      if (!Array.isArray(repos) || repos.length === 0) {
        return respond(400, { error: 'repos array required' });
      }

      const org = getOrg();
      const results = [];

      for (const r of repos) {
        const repoName = r.name || r;
        const repoOwner = r.owner || org;

        try {
          const template = getCiTemplate(stack || r.stack || 'default', repoOwner);
          const content = Buffer.from(template).toString('base64');

          // Check if exists
          const checkRes = await fetch(
            `${GITHUB_API}/repos/${repoOwner}/${repoName}/contents/.github/workflows/ci.yml`,
            { headers: getHeaders() }
          );

          if (checkRes.status === 200) {
            results.push({ repo: repoName, status: 'skipped', message: 'Already has ci.yml' });
            continue;
          }

          // Create
          const createRes = await fetch(
            `${GITHUB_API}/repos/${repoOwner}/${repoName}/contents/.github/workflows/ci.yml`,
            {
              method: 'PUT',
              headers: getHeaders(),
              body: JSON.stringify({
                message: 'chore: add ForgeOps CI/CD pipeline [skip ci]',
                content: content,
              }),
            }
          );

          if (createRes.status === 201) {
            results.push({ repo: repoName, status: 'created', message: 'CI template added' });
          } else {
            const err = await createRes.json();
            results.push({ repo: repoName, status: 'error', message: err.message || `HTTP ${createRes.status}` });
          }
        } catch (err) {
          results.push({ repo: repoName, status: 'error', message: err.message });
        }

        // Small delay to avoid rate limiting
        await new Promise(resolve => setTimeout(resolve, 200));
      }

      const created = results.filter(r => r.status === 'created').length;
      const skipped = results.filter(r => r.status === 'skipped').length;
      const errors = results.filter(r => r.status === 'error').length;

      console.log(`Bulk onboard: ${created} created, ${skipped} skipped, ${errors} errors out of ${repos.length}`);

      return respond(200, {
        summary: { total: repos.length, created, skipped, errors },
        results,
      });
    }

    // GET /template
    if (segments[0] === 'template' && method === 'GET') {
      const stack = query.stack || 'default';
      const org = query.org || getOrg();
      return respond(200, {
        filename: '.github/workflows/ci.yml',
        content: getCiTemplate(stack, org),
        stack,
      });
    }

    return respond(404, { error: 'Not found' });
  } catch (err) {
    console.error('Onboarding function error:', err.message);
    return respond(500, { error: err.message });
  }
};
