#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# forgeops-summary.sh — Generate final pipeline summary from event log
#
# Reads .forgeops/events.json and writes a complete Markdown summary to
# GITHUB_STEP_SUMMARY including a header, events table, statistics, and footer.
###############################################################################

EVENTS_DIR="${GITHUB_WORKSPACE:-.}/.forgeops"
EVENTS_FILE="${EVENTS_DIR}/events.json"

# ─── Pre-flight checks ───────────────────────────────────────────────────────
if [[ -z "${GITHUB_STEP_SUMMARY:-}" ]]; then
  echo "[forgeops-summary] GITHUB_STEP_SUMMARY not set — writing to stdout instead"
  GITHUB_STEP_SUMMARY="/dev/stdout"
fi

if [[ ! -f "${EVENTS_FILE}" ]]; then
  echo "[forgeops-summary] No events file found at ${EVENTS_FILE} — nothing to summarise"
  {
    echo "## ForgeOps Pipeline Summary"
    echo ""
    echo "> No events were recorded during this run."
  } >> "${GITHUB_STEP_SUMMARY}"
  exit 0
fi

# ─── Read events and compute stats ───────────────────────────────────────────
PASSED=0
FAILED=0
SKIPPED=0
INFO=0
TOTAL=0

while IFS= read -r line; do
  [[ -z "${line}" ]] && continue
  TOTAL=$((TOTAL + 1))

  # Extract status field with simple pattern match (no jq dependency)
  status=""
  if [[ "${line}" =~ \"status\":\"([a-z]+)\" ]]; then
    status="${BASH_REMATCH[1]}"
  fi

  case "${status}" in
    passed)  PASSED=$((PASSED + 1)) ;;
    failed)  FAILED=$((FAILED + 1)) ;;
    skipped) SKIPPED=$((SKIPPED + 1)) ;;
    info)    INFO=$((INFO + 1)) ;;
  esac
done < "${EVENTS_FILE}"

# ─── Determine overall result ────────────────────────────────────────────────
if [[ ${FAILED} -gt 0 ]]; then
  OVERALL_ICON=":x:"
  OVERALL_STATUS="FAILED"
elif [[ ${PASSED} -eq 0 && ${SKIPPED} -gt 0 ]]; then
  OVERALL_ICON=":fast_forward:"
  OVERALL_STATUS="SKIPPED"
else
  OVERALL_ICON=":white_check_mark:"
  OVERALL_STATUS="PASSED"
fi

# ─── Helper: status icon ─────────────────────────────────────────────────────
status_icon() {
  case "${1}" in
    passed)  echo ":white_check_mark:" ;;
    failed)  echo ":x:" ;;
    skipped) echo ":fast_forward:" ;;
    info)    echo ":information_source:" ;;
    *)       echo ":grey_question:" ;;
  esac
}

# ─── Write summary ───────────────────────────────────────────────────────────
{
  # Header
  REPO="${GITHUB_REPOSITORY:-"unknown/unknown"}"
  RUN_ID="${GITHUB_RUN_ID:-"local"}"
  RUN_NUMBER="${GITHUB_RUN_NUMBER:-"0"}"
  SHA="${GITHUB_SHA:-"0000000"}"
  SHORT_SHA="${SHA:0:7}"

  echo "## ${OVERALL_ICON} ForgeOps Pipeline — ${OVERALL_STATUS}"
  echo ""
  echo "| Property | Value |"
  echo "|----------|-------|"
  echo "| Repository | \`${REPO}\` |"
  echo "| Run | \`#${RUN_NUMBER}\` |"
  echo "| Commit | \`${SHORT_SHA}\` |"
  echo "| Triggered by | \`${GITHUB_ACTOR:-"unknown"}\` |"
  echo ""

  # Events table
  echo "### Pipeline Events"
  echo ""
  echo "| | Event | Status | Message | Timestamp |"
  echo "|---|-------|--------|---------|-----------|"

  while IFS= read -r line; do
    [[ -z "${line}" ]] && continue

    evt="" sts="" msg="" ts=""
    [[ "${line}" =~ \"event_type\":\"([^\"]+)\" ]] && evt="${BASH_REMATCH[1]}"
    [[ "${line}" =~ \"status\":\"([^\"]+)\" ]]     && sts="${BASH_REMATCH[1]}"
    [[ "${line}" =~ \"message\":\"([^\"]+)\" ]]     && msg="${BASH_REMATCH[1]}"
    [[ "${line}" =~ \"timestamp\":\"([^\"]+)\" ]]   && ts="${BASH_REMATCH[1]}"

    ICON="$(status_icon "${sts}")"
    echo "| ${ICON} | \`${evt}\` | ${sts} | ${msg} | \`${ts}\` |"
  done < "${EVENTS_FILE}"

  echo ""

  # Stats
  echo "### Statistics"
  echo ""
  echo "| Metric | Count |"
  echo "|--------|-------|"
  echo "| :white_check_mark: Passed | ${PASSED} |"
  echo "| :x: Failed | ${FAILED} |"
  echo "| :fast_forward: Skipped | ${SKIPPED} |"
  echo "| :information_source: Info | ${INFO} |"
  echo "| **Total** | **${TOTAL}** |"
  echo ""

  # Footer
  SERVER_URL="${GITHUB_SERVER_URL:-"https://github.com"}"
  if [[ "${RUN_ID}" != "local" ]]; then
    RUN_LINK="${SERVER_URL}/${REPO}/actions/runs/${RUN_ID}"
    echo "---"
    echo ""
    echo ":link: [View full run details](${RUN_LINK})"
  else
    echo "---"
    echo ""
    echo "_Run executed locally — no GitHub Actions link available._"
  fi

  echo ""
  echo "_Generated by ForgeOps Pipeline at $(date -u +"%Y-%m-%dT%H:%M:%SZ")_"
} >> "${GITHUB_STEP_SUMMARY}"

echo "[forgeops-summary] Summary written — ${TOTAL} events (${PASSED} passed, ${FAILED} failed, ${SKIPPED} skipped, ${INFO} info)"
